### ISSUE TITLE
Bouton d'ajout de recette manquant

### ISSUE THREAD

**Issue by aranega** [314r/joliebulle#124]
Le bouton d'ajout de recette manque (est masqué/mal affiché) depuis la version 3.6 

![jb](https://cloud.githubusercontent.com/assets/2317394/19489383/5298e2e4-956b-11e6-90a8-d5ddeba6e44e.png)

Le soucis arrive chez moi sur 2 machines (archlinux et manjaro), version 3.6 et version toute fraîche depuis les repos.
Après inspection du DOM, il semblerait que le bouton est tout simplement masqué par l'input de recherche un peu trop long. J'ai réussis à le réafficher en modifiant `library.css` comme ceci:

```css
.recipe-list-header input{
    border:none;
    height:55px;
    width:53%;   // on fixe la longeur de l'input 
    margin:auto;
    background-color: #fff;
    border-bottom: 1px solid #eee;
}
```
Et le résultat:
![jbok](https://cloud.githubusercontent.com/assets/2317394/19489505/cb6a89d4-956b-11e6-997e-ed0dbab3b96c.png)

Par contre, je suis un peu tout naze en CSS, c'est peut être pas la bonne façon de faire.
